version: "3.8"

services:
  nginx:
    image: nginx:alpine
    platform: linux/amd64
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    platform: linux/amd64
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: votacion
    ports:
      - "3306:3306"
    volumes:
      - ./bd/votaciones.sql:/docker-entrypoint-initdb.d/votaciones.sql
